language: objective-c
osx_image: xcode8

before_install:
  - pod repo update --silent
  - gem install xcpretty

install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace RandomUser.xcworkspace -scheme 'RandomUser' -destination 'platform=iOS Simulator,name=iPhone 6' build test CODE_SIGN_IDENTITY=- | xcpretty -c
